[book]
authors = ["Joeyh021"]
language = "en"
multilingual = false
src = "src"
title = "Computer Systems Engineering Notes"

[preprocessor.katex]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Joeyh021/first-year-notes"

[output.html.fold]
enable = true