
name: Deploy on Server

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: run deploy script on remote server
      uses: fifsky/ssh-action@master
      with:
        command: cd notes && git pull && mdbook build
        host: ${{ secrets.HOST }}
        user: ubuntu
        key: ${{ secrets.PRIVATE_KEY}}
    

